### ISSUE TITLE
Entities spawned during the entities post-import script are unpacked

### ISSUE THREAD

**Issue by PeterVerzijl** [heygleeson/godot-ldtk-importer#10]
When placing Godot scenes during the entities post-import script; the scenes are unpacked and lose their 'prefab' status in the editor. This is due to the recursive set owner setting all sub nodes (including spawned sub-scenes and all of their children) to the world node.

```gdscript
for node in level.get_children():
	Util.recursive_set_owner(node, world)
```

The intended effect is that all of the scenes which are spawned during post-import scripts are kept as sub-scenes with their 'Open in Editor' icon in tact. This keeps the reference to the scene and I can update all spawned scenes by just editing the scene for the entity.

![image](https://github.com/heygleeson/godot-ldtk-importer/assets/5670225/099fe834-b023-4b5c-afcd-fcb19a2521c5)

A fix that I use is to place the post-import script for entities *after* the recursive set owner and set the owner of the sub-scene root node to the layer by hand. However; this is probably not workable as a general fix.

```gdscript
if (Util.options.entities_post_import):
var layers = level.get_children()
for layer in layers:
	if not layer is LDTKEntityLayer:
		continue

	if (Util.options.verbose_output):
		var entityLayerName = layer.get_parent().name + "." + layer.name
		print("\n::POST-IMPORT ENTITIES: ", entityLayerName)
```

What probably needs to happen is that when traversing the tree to set the owners; spawned sub-scenes in post-import scripts only have their root node set the owner of; but not their children.

**Comment by heygleeson** [comment]
Thanks for the report! Apologies for the delay. This have been fixed in [v2.0.1](https://github.com/heygleeson/godot-ldtk-importer/releases/tag/2.0.1)
