### ISSUE TITLE
How to use Y-Sort?

### ISSUE THREAD

**Issue by shinaka** [heygleeson/godot-ldtk-importer#13]
Normally you have to enable Y-Sorting on a per-layer basis on the Tilemap - but since the Tilemap is created via import and can't be edited, is there a different way of accomplishing this?

**Comment by heygleeson** [comment]
You can write a Level Post-Import script that will set `y_sort_enabled` on each TileMap node. You can adapt this script to further specify which TileMaps/Layers you want to toggle.

```gdscript
@tool

## Level Post-Import: Add Y-Sort

func post_import(level: LDTKLevel) -> LDTKLevel:

	for child in level.get_children():
		if not child is TileMap:
			continue

		# Set Y-Sort on TileMap node
		child.y_sort_enabled = true

		# Set Y-Sort for all TileMap layers
		for index in range(child.get_layers_count()):
			child.set_layer_y_sort_enabled(index, true)

	return level
```
