### ISSUE TITLE
Simplify tile flipping

### ISSUE THREAD

**Issue by monkeez** [heygleeson/godot-ldtk-importer#14]
I think it might be possible to simplify the code that flips tiles since tile flipping was added back to Godot 4.2 (without the need to create alternative tiles).

**Comment by heygleeson** [comment]
As far as I can tell, unfortunately not!

The new improvements in Godot 4.2 seem to make it easier to flip tiles *inside* the editor, but under the hood it seems to work by still using alternative tiles (but in some undocumented way). For our purposes, there does not seem to be a new way to programatically flip a tile at a particular grid cell.

**Comment by monkeez** [comment]
It's been a while since I looked at it but I think this comment had info on how to do it:

https://github.com/godotengine/godot-proposals/issues/3967#issuecomment-1675438561

**Comment by heygleeson** [comment]
Happy to tell you it's now been implemented! Will be out in the next update - significantly reduces the amount of necessary alternative tiles generated.

**Comment by heygleeson** [comment]
Fixed in [v2.0.1](https://github.com/heygleeson/godot-ldtk-importer/releases/tag/2.0.1)
