### ISSUE TITLE
Seperating levels into individuals scenes

### ISSUE THREAD

**Issue by Ariber-Yadier** [heygleeson/godot-ldtk-importer#15]
I want to procedurally generate a world for my game where the level order is randomly generated and to do that, I need to randomly instantiate the levels. But, as far as I know, there is no way to do that currently.

**Comment by heygleeson** [comment]
It's a feature I intend to support, but has implications when handling EntityRefs outside the level itself - they would have nothing to point to.

This likely might not matter to most people so I would have it set it up as an import flag. I 'll have another look at this soon.

**Comment by vi-sa-vie** [comment]
Adding +1 to this feature request because [Metroidvania System](https://github.com/KoBeWi/Metroidvania-System) requires levels to be scenes and it would be incredible to use these add-ons alongside each other.

**Comment by heygleeson** [comment]
Added in V1.3
