### ISSUE TITLE
Load errors "an incoming node's name clashes with [...]"

### ISSUE THREAD

**Issue by OmegaBowser** [heygleeson/godot-ldtk-importer#18]
![Screenshot 2024-06-11 151451](https://github.com/heygleeson/godot-ldtk-importer/assets/4289190/cc5d87c2-817a-40ca-b61a-56314453277c)

Having this error when important and updating a map from LDTK.
It doesn't seem to be blocking or crashing anything, but it's still annoying.

When I re move the ldtk scene file, no more error.

What could go wrong with my map ? 
It only has 4 layers, and basic entities with attributes.

**Comment by Nrosa01** [comment]
I have the same issue but worse because it renames internal nodes of the entities I spawn which breaks dependencies for the script as I use unique names and with this I can`t

**Comment by heygleeson** [comment]
Thanks for the report! Can you test this in [v2.0.1](https://github.com/heygleeson/godot-ldtk-importer/releases/tag/2.0.1) and tell me if this issue has been fixed?

**Comment by Nrosa01** [comment]
It seems to be fixed! I have to check what you did because I tried long time ago to solve on my own and didn't find the cause ><
I have only done a quick test but it failed before and it doesn't now so I think it´s perfect 👌🏻. Thank you! ^^

**Comment by heygleeson** [comment]
You are welcome! Glad to have helped.
