### ISSUE TITLE
LDtk Level Properties - "Bg Image" Anchor point not being used / recognized

### ISSUE THREAD

**Issue by kaiiboraka** [heygleeson/godot-ldtk-importer#23]
The default behavior of a level's Bg image is to anchor to the top left corner, but LDtk (must have recently) added the option to change the anchor position to any main position, but I do not think this setting is read by this importer.

Here it is in LDtk, where I have updated my bg image to be anchored in the bottom left
![image](https://github.com/user-attachments/assets/2e3643c2-3345-43ba-9ef0-000fbae001ab)

And here it is in Godot where it's still in the top left.
![image](https://github.com/user-attachments/assets/ffad6420-e2dc-4765-9e86-87d8c9e8fcb0)

I'm using LDtk 1.5.3, and Godot version 4.3.beta2.mono, and LDtk Importer v 1.2.

I'm relatively new to this issue-posting business, please let me know if there's any other potential useful information you'd like from me. Thank you.

**Comment by heygleeson** [comment]
Fixed in 1.3! Thanks for the report.
