### ISSUE TITLE
Collisions clear every time I save ldtk / Reimport

### ISSUE THREAD

**Issue by Ethanscharlie** [heygleeson/godot-ldtk-importer#31]
Not sure if this is intended or if there is already some intended script solution but this is annoying
~Thanks

**Comment by Ethanscharlie** [comment]
Also to add tile physics to the tileset I have to delete the atlas and then reimport and then it lets me, but on default it just doesn't have the physics tab at all

**Comment by heygleeson** [comment]
The default import behaviour is that generated TileSets should preserve their data on reimporting. Physics Layers should be kept unless `Force TileSet Reimport` is ON, or something has gone wrong.

Can you test this in [v2.0.1](https://github.com/heygleeson/godot-ldtk-importer/releases/tag/2.0.1)?

**Comment by avivajpeyi** [comment]
I was having the same issue until i turned `Force TileSet Reimport` off!

**Comment by Sewdohe** [comment]
I am having this issue even though I've turned `Force TileSet Reimport` off! D:

**Comment by LeviLovie** [comment]
Thank you, @dbrats. That solved the issue. I made a pull request with your fix.
