### ISSUE TITLE
Error: Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.

### ISSUE THREAD

**Issue by Nrosa01** [heygleeson/godot-ldtk-importer#7]
This error appears when importing or reimporting and it's annoying. Godot doesn't tell me which line throw it so I'm not sure where to start looking to fix it

![image](https://github.com/heygleeson/godot-ldtk-importer/assets/62796415/9b220258-528b-4e79-b2c6-ee247f732e9d)

**Comment by heygleeson** [comment]
Can you confirm your Godot version? My memory's not great but I think this was a bug related to Tilesets/Tilemaps in 4.0/4.1.

**Comment by Nrosa01** [comment]
Oh, my godot version is 4.1.2, I guess I'll try 4.2, I was afraid of updating because I'm afraid of the unstability it can introduce
